spring:
 application:
  name: zuul redis:
   host: localhost
   port: 6379
 
server:
  port: 9999
  
  
zuul:
  retryable: true
  routes:
    add:
      path: /adds/**
      serviceId: add
      stripPrefix: false
    substract: 
      path: /subs/**
      serviceId: substract
      stripPrefix: false
    multiplation:
      path: /muls/**
      serviceId: multiplation
      stripPrefix: false
    devide:
      path: /devs/**
      serviceId: devide
      stripPrefix: false
  ribbon-isolation-strategy: thread
  thread-pool:
    use-separate-thread-pools: true
    thread-pool-key-prefix: zuul-
     
  ratelimit:
    key-prefix: true
    enabled: true
    repository: REDIS
    policy-list:
      add:
        - limit: 10
          refresh-interval: 20
          type:
          - origin
      substract:
        - limit: 10
          refresh-interval: 20
          type:
          - origin
          - user
      multiplation:
        - limit: 8
          refresh-interval: 20
          type:
          - origin
          - url
      devide:
        - limit: 13
          refresh-interval: 20
          type:          - origin
  
      
      
eureka:
  instance:
    non-secure-port: ${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      

hystrix:
  command:
   add:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
   substract:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
   multiplation:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
   devide:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

threadpool:
    zuul-add:
      coreSize: 30
      maximumSize: 100
      allowMaximumSizeToDivergeFromCoreSize: true
    zuul-substract:
      coreSize: 30
      maximumSize: 100
      allowMaximumSizeToDivergeFromCoreSize: true
    zuul-multiplation:
      coreSize: 30
      maximumSize: 100
      allowMaximumSizeToDivergeFromCoreSize: true
    zuul-devide:
      coreSize: 30
      maximumSize: 100
      allowMaximumSizeToDivergeFromCoreSize: true
 
           
 
add: 
  ribbon:
    MaxAutoRetriesNextServer: 1
    ReadTimeout: 3000
    ConnectTimeout: 1000
    MaxTotalConnections: 300
    MaxConnectionsPerHost: 100

substract:
  ribbon:
    MaxAutoRetriesNextServer: 1
    ReadTimeout: 3000
    ConnectTimeout: 1000
    MaxTotalConnections: 300
    MaxConnectionsPerHost: 100
 
multiplation:
  ribbon:
    MaxAutoRetriesNextServer: 1
    ReadTimeout: 3000
    ConnectTimeout: 1000
    MaxTotalConnections: 300
    MaxConnectionsPerHost: 100
    
devide:
  ribbon:
    MaxAutoRetriesNextServer: 1
    ReadTimeout: 3000
    ConnectTimeout: 1000
    MaxTotalConnections: 300
    MaxConnectionsPerHost: 100
    
logging:
   level:
      com.netflix.loadbalancer.LoadBalancerContext: debug
      
      