spring:
 application:
  name: zuul
  
  
server:
  port: 9999
  
  
zuul:
  routes:
    add:
      path: /add/**
      serviceId: add
      stripPrefix: false
    substract: 
      path: /substract/**
      serviceId: substract
      stripPrefix: false
    multiplation:
      path: /multiplation/**
      serviceId: multiplation
      stripPrefix: false
    devide:
      path: /divide/**
      serviceId: divide
      stripPrefix: false
    ribbon-isolation-strategy: thread
  ratelimit:
    key-prefix: true    enabled: true
    repository: JPA
    policy-list:      add:
        - limit: 5
          refresh-interval: 60
          type:          - origin
      substract:
        - limit: 10
          refresh-interval: 50
          type:          - origin
          - user
      multiplation:
        - limit: 8
          refresh-interval: 30
          type:          - origin
          - url
      devide:
        - limit: 13
          refresh-interval: 40
          
      
eureka:
  instance:
    non-secure-port: ${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
    product:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
  threadpool:
    zuul-product:
      coreSize: 30
      maximumSize: 100
      allowMaximumSizeToDivergeFromCoreSize: true
    zuul-display:
      coreSize: 30
      maximumSize: 100
      allowMaximumSizeToDivergeFromCoreSize: true

add: 
  ribbon:
    MaxAutoRetriesNextServer: 1
    ReadTimeout: 3000
    ConnectTimeout: 1000
    MaxTotalConnections: 300
    MaxConnectionsPerHost: 100

substract:
  ribbon:
    MaxAutoRetriesNextServer: 1
    ReadTimeout: 3000
    ConnectTimeout: 1000
    MaxTotalConnections: 300
    MaxConnectionsPerHost: 100
 
multiplation:
  ribbon:
    MaxAutoRetriesNextServer: 1
    ReadTimeout: 3000
    ConnectTimeout: 1000
    MaxTotalConnections: 300
    MaxConnectionsPerHost: 100
    
devide:
  ribbon:
    MaxAutoRetriesNextServer: 1
    ReadTimeout: 3000
    ConnectTimeout: 1000
    MaxTotalConnections: 300
    MaxConnectionsPerHost: 100
      
      