management:
  endpoints:
    web:
      exposure:
        include: refresh
        
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka  # default address
 